- name:             Ethereum Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0x7CD383AAF392147b79dB633DC16642B720A173d0'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'changeme'

- name:             Ethereum Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0x7CD383AAF392147b79dB633DC16642B720A173d0'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'test'

- name:             Trust Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0x7CD383AAF392147b79dB633DC16642B720A173d0'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'changeme'

- name:             Trust Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0x7CD383AAF392147b79dB633DC16642B720A173d0'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'test'
